### PR TITLE
Fix ARM64ImmInstruction functionality

### LINKED ISSUE #4165: ARM64ImmInstruction should not have a symbol reference
That's what `ARM64ImmSymInstruction` is for.  Investigate why the `Imm` form has a symbol reference and remove it.

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Make ARM64ImmInstruction a base class purely for immediate values by removing
  unnecessary functionality
* Correct Imm instruction binary encoding
* Rebase the ARM64SynchronizationInstruction to extend ARM64ImmediateInstruction
  and share functionality

Fixes #4165

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@knn-k , please review

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

File: compiler/aarch64/codegen/ARM64Instruction.hpp [hunk 1]
```diff
@@ -188,29 +132,14 @@ class ARM64ImmInstruction : public TR::Instruction
...
-    * @param[in] sr : symbol reference
-    * @return symbol reference
-    */
-   TR::SymbolReference *setSymbolReference(TR::SymbolReference *sr)
+   virtual void insertImmediateField(uint32_t *instruction)
       {
-      return (_symbolReference = sr);
+      // Overlay the 32-bit immediate with no masking or shifting
+      //
+      *instruction |= _sourceImmediate;
```
Comment (knn-k) [inline compiler/aarch64/codegen/ARM64Instruction.hpp]: I think `*instruction = _sourceImmediate;` (no ORing) is better here.

File: compiler/aarch64/codegen/GenerateInstructions.cpp [hunk 2]
```diff
@@ -44,30 +44,14 @@ TR::Instruction *generateInstruction(TR::CodeGenerator *cg, TR::InstOpCode::Mnem
    return new (cg->trHeapMemory()) TR::Instruction(op, node, cg);
    }
 
-TR::Instruction *generateImmInstruction(TR::CodeGenerator *cg, TR::InstOpCode::Mnemonic op, TR::Node *node, uint32_t imm,
+TR::ARM64ImmInstruction *generateImmInstruction(TR::CodeGenerator *cg, TR::InstOpCode::Mnemonic op, TR::Node *node, uint32_t imm,
```
Comment (knn-k) [inline compiler/aarch64/codegen/GenerateInstructions.cpp]: Should we also change the return types of other `generateXXXInstruction()` to make them consistent?

File: compiler/aarch64/codegen/ARM64Instruction.hpp (hunk 1 above)
Comment (0xdaryl) [reply compiler/aarch64/codegen/ARM64Instruction.hpp]: I had something in mind last Friday when I wrote this, but alas I can't think of a current, useful example where OR'ing would be the behaviour you want.  I'll change it to a store.  It's easy enough to change in the future should this not be the behaviour we want.

Comment (0xdaryl) [reply compiler/aarch64/codegen/ARM64Instruction.hpp]: Fixed in ff0a1face9a3264be38edd9e7b232d5457975c7b

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

File: compiler/aarch64/codegen/GenerateInstructions.cpp (hunk 2 above)
Comment (0xdaryl) [reply compiler/aarch64/codegen/GenerateInstructions.cpp]: Yes, but that's beyond the scope of this PR.  I created issue #4179 to track this work.

**Comment by 0xdaryl** [comment]
@fjeremic @Leonardo2718 : would one of you mind reviewing and merging this please?

File: compiler/aarch64/codegen/ARM64Instruction.hpp [hunk 3]
```diff
@@ -2669,30 +2599,12 @@ class ARM64SynchronizationInstruction : public TR::Instruction
...
-    * @return source immediate
-    */
-   uint32_t setSourceImmediate(uint32_t si) {return (_sourceImmediate = si);}
-
-   void insertImmediateField(uint32_t *instruction)
+   virtual void insertImmediateField(uint32_t *instruction)
       {
-      TR_ASSERT(_sourceImmediate <= 0xF, "Immediate value exceeds 4 bits.");
-      *instruction |= ((_sourceImmediate & 0xF) << 8);
+      TR_ASSERT(constantIsUnsignedImm4(getSourceImmediate()), "Immediate value exceeds 4 bits.");
```
Comment (fjeremic) [inline compiler/aarch64/codegen/ARM64Instruction.hpp]: This sounds like a fatal assert. If we cannot encode the immediate the program is not functionally correct.

Comment (0xdaryl) [reply compiler/aarch64/codegen/ARM64Instruction.hpp]: Agree.  Fixed.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64
