### PR TITLE
AArch64: Binary Encoding Fix and Addition of 'B' and 'BL' Instructions

### LINKED ISSUE #3017: AArch64: Branch instructions are unavailable
`B` (unconditional branch with PC-relative offset) and `BL` (branch and link with PC-relative offset) instructions are missing in OMRInstOpCodeEnum.hpp and OpBinary.cpp for aarch64.

### PR DESCRIPTION
**Pull request by marufunb**
Some binary encoding values mismatched because of the mismatch in opcodes.
Those values are being updated. 'B' and 'BL' instructions are being added
 to ORMInstOpCodeEnum.cpp and OpBinary.cpp

Fixes #3017 
Signed-off-by: marufunb <mrahma15@unb.ca>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by aarongraham9** [comment]
Please have a look @0xdaryl, @knn-k and @jeanlego at Maruf's first PR when you get a chance.

**Comment by knn-k** [comment]
Re: @0xdaryl's comment:
Is it better to separate the string list in `opCodeToNameMap[]` in `ARM64Debug.cpp` to a `.hpp` file, like `OMRInstOpCodeEnum.hpp`?

**Comment by knn-k** [comment]
I changed the dash signs in the following comments in `OpBinary.cpp` to ASCII minus signs before, as I preferred ASCII-only files.
```
/* Data processing – Immediate */
/* Data Processing – register */
```

@0xdaryl Is there any guideline for the characters to be used in the source code?

**Comment by jeanlego** [comment]
I agree with you, I don't see the value of the change there, probably slipped by Maruf. Other than the branch instruction and the binary encoding changes, I don't see the point of the other changes. @marufunb

File: compiler/aarch64/codegen/OpBinary.cpp [hunk 1]
```diff
@@ -309,8 +311,8 @@ const OMR::ARM64::InstOpCode::OpCodeBinaryEntry OMR::ARM64::InstOpCode::binaryEn
 		0xD3400000,	/* UBFM      	ubfmx	 */
 	/* Extract */
 		0x13800000,	/* EXTR      	extrw	 */
-		0x93C00000,	/* EXTR      	extrx	 */
-/* Data Processing - register */
+		0x93C08000,	/* EXTR      	extrx	 */
+/* Data Processing – register */
```
Comment (aarongraham9) [inline compiler/aarch64/codegen/OpBinary.cpp]: Looks like you missed this hyphen, n-dash, m-dash etc. The other one looks to be fixed now.

**Comment by aarongraham9** [comment]
Also not sure what, if anything, the out of order Fixes # and the signing will do to the IP scan.

```
Signed-off-by: marufunb <mrahma15@unb.ca>
Fixes #3087
```

**Comment by aarongraham9** [comment]
Thanks, @marufunb for the minus-sign fix.

I didn't mean to have you remove the `Fixes #3087`; I was just commenting it should probably come **before** the signoff `Signed-off-by: marufunb <mrahma15@unb.ca>` (Please see the [Contributing Guide's Example commits section](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md) for more information).

Please put back the `Fixes #3087` before the signoff `Signed-off-by: marufunb <mrahma15@unb.ca>`.

**Comment by aarongraham9** [comment]
Attaching the latest copy of the Instruction/Binary Encoding Generation Spreadsheet **[2018.10.22]**: [AArch64_ops.2018.10.22.xlsx](https://github.com/eclipse/omr/files/2503000/AArch64_ops.2018.10.22.xlsx)

Also mirrored in our CAS-Atlantic repo [AArch64_ops.2018.10.22.xlsx](https://github.com/CAS-Atlantic/AArch64-Encoding/blob/055f60434188aecb9021f2c515314d7daecd88e0/AArch64_ops.xlsx) in commit CAS-Atlantic/AArch64-Encoding@055f60434188aecb9021f2c515314d7daecd88e0.

**Comment by aarongraham9** [comment]
Also @marufunb it should be `Fixes #3017` (the corresponding issue) **not** #3087 (this PR).

**Comment by knn-k** [comment]
@marufunb I am fine with the changes in the code.

File: compiler/compile/OMRSymbolReferenceTable.cpp [hunk 2]
```diff
@@ -1303,7 +1303,7 @@ OMR::SymbolReferenceTable::findOrCreateClassSymbol(
    sym->setClassObject();
 
 #ifdef J9_PROJECT_SPECIFIC
-   if (cpIndex == -1 && comp()->compileRelocatableCode())
+   if (cpIndex == -1 && comp()->compileRelocatableCode() && !comp()->getOption(TR_UseSymbolValidationManager))
```
Comment (aarongraham9) [inline compiler/compile/OMRSymbolReferenceTable.cpp]: Is this an intended change?

File: compiler/compile/OMRSymbolReferenceTable.cpp [hunk 3]
```diff
@@ -1303,7 +1303,7 @@ OMR::SymbolReferenceTable::findOrCreateClassSymbol(
    sym->setClassObject();
 
 #ifdef J9_PROJECT_SPECIFIC
-   if (cpIndex == -1 && comp()->compileRelocatableCode())
+   if (cpIndex == -1 && comp()->compileRelocatableCode()
```
Comment (aarongraham9) [inline compiler/compile/OMRSymbolReferenceTable.cpp]: Now you've removed a `)`. Did you try and compile this? It shouldn't compile as-is.

**Comment by aarongraham9** [comment]
Also please rebase off of the `master` branch now that there are merge conflicts. Although if you didn't intend the change in `compiler/compile/OMRSymbolReferenceTable.cpp` then this would go away if you negate your change.

**Comment by knn-k** [comment]
LGTM.

**Comment by jeanlego** [comment]
Lgtm! 
Good job! Finding the encoding error cannot have been a trivial task! :)

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by aarongraham9** [comment]
LGTM after fixing the permissions.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64
