### PR TITLE
Choose correct dwarfdump for osx ddrgen

### LINKED ISSUE #3708: ddrgen on OSX fails with some versions of dwarfdump
On Mac OSX, there seems to be two versions of dwarfdump. One is `llvm-dwarfdump`, which is tied to clang, and `dwarfdump-classic` which is based on dwarfutils. 

When ddrgen was first ported to Mac OSX, calling `dwarfdump` would invoke the `dwarfdump-classic` version. However, somewhat recently, it was changed so `dwarfdump` links to `llvm-dwarfdump` instead. This may have been caused by the Mojave update, or the 10.2 update to XCode, or a recent update.

Ddrgen's parser relies on the format that `dwarfdump-classic` outputs, so we need to specify we want the classic dwarfdump instead of the llvm based one. 

On systems where `dwarfdump` is not a symlink to `llvm-dwardump`, there is no `dwarfdump-classic` binary, and it is just called `dwarfdump`.

fyi @keithc-ca

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
Sometimes on Mac OSX, dwarfdump is linked to "llvm-dwarfdump", which outputs a different format than the version of dwarfdump assumed by ddrgen. This change will select the correct version of dwarfdump to use on those systems that select the wrong version for ddrgen.

Signed-off-by: mikezhang <mike.h.zhang@ibm.com>

Fixes #3708

fyi: @keithc-ca

### CODE REVIEW

File: ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp [hunk 1]
```diff
@@ -79,9 +79,51 @@ dwarf_init(int fd,
...
+		 * "llvm-dwarfdump". If we don't find "dwarfdump-classic", then the machine
+		 * we are on uses the correct version of dwarfdump.
+		 */
+		stringstream toolpath;
+		fp = popen("xcrun -f dwarfdump-classic 2>&1", "r");
+		if (NULL != fp) {
+			char *buffer = NULL;
+			size_t cap = 0;
+			size_t len = getline(&buffer, &cap, fp);
+			if ((-1 == len) || (buffer[0] != '/')) {
```
Comment (keithc-ca) [inline ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: `getline()` returns `ssize_t`, not `size_t`.

File: ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp [hunk 2]
```diff
@@ -79,9 +79,51 @@ dwarf_init(int fd,
...
+				if ((-1 != len) && (buffer[0] != '/')) {
+					free(buffer);
```
Comment (keithc-ca) [inline ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: There's no need to free buffer here: we can use it again below.

File: ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp [hunk 3]
```diff
@@ -79,9 +79,51 @@ dwarf_init(int fd,
...
+					setError(error, DW_DLE_IOF);
+				}
+				len = getline(&buffer, &cap, fp);
+				if ((-1 == len) || (buffer[0] != '/')) {
+					ret = DW_DLV_ERROR;
+					setError(error, DW_DLE_IOF);
+				}
+			}
+			/* remove the newline consumed by getline */
+			if ('\n' == buffer[len - 1]) {
```
Comment (keithc-ca) [inline ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: This should also check that `len > 0`.

**Comment by charliegracie** [comment]
@keithc-ca have your comments been addressed sufficiently?

File: ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp (hunk 1 above)
Comment (keithc-ca) [reply ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: The coding standard prefers `'/' != buffer[0]` over `buffer[0] != '/'`.
Rather than make assumptions, I think this should check `NULL != buffer` before dereferencing that pointer.
These comments apply here and in similar situations below.

File: ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp [hunk 4]
```diff
@@ -79,9 +79,48 @@ dwarf_init(int fd,
...
+				if ((-1 == len) || (buffer[0] != '/')) {
+					ret = DW_DLV_ERROR;
+					setError(error, DW_DLE_IOF);
+				}
+			}
+			/* remove the newline consumed by getline */
+			if ((len > 0) && ('\n' == buffer[len - 1])) {
+				buffer[len - 1] = '\0';
+			}
+			toolpath << buffer;
```
Comment (keithc-ca) [inline ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: `buffer` could be `NULL` here (if no dwarfdump is available).

Comment (mikezhang1234567890) [reply ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: I don't believe so. From `man getline` on OSX:
```
RETURN VALUES
     The getdelim() and getline() functions return the number of characters written, excluding the terminating NUL character.  The value -1 is
     returned if an error occurs, or if end-of-file is reached.
```
So if `len != -1` this means that characters are successfully read into the buffer.

**Comment by mikezhang1234567890** [comment]
@keithc-ca I refactored that part so there should be no more possibility of accessing a null pointer.

File: ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp [hunk 5]
```diff
@@ -79,9 +79,52 @@ dwarf_init(int fd,
...
+		/* On some Mac machines, calling "dwarfdump" in shell calls a version named
+		 * "llvm-dwarfdump" instead of the version of dwarfdump DDR uses, which is
+		 * instead named "dwarfdump-classic" on those systems. Thus, we first try to
+		 * find "dwarfdump-classic" directly in case "dwarfdump" is linked to
+		 * "llvm-dwarfdump". If we don't find "dwarfdump-classic", then the machine
+		 * we are on uses the correct version of dwarfdump.
+		 */
+		fp = popen("xcrun -f dwarfdump-classic 2>/dev/null", "r");
+		if (NULL == fp) {
+			fp = popen("xcrun -f dwarfdump 2>/dev/null", "r");
```
Comment (keithc-ca) [inline ddr/lib/ddr-scanner/dwarf/DwarfParser.cpp]: I don't like that this `popen` call is duplicated below. Perhaps we need a helper function that does the `popen`, `getline` and path check, so the flow here could be something like this:
```
if (toolCheck(&toolpath, "xcrun -f dwarfdump-classic 2>/dev/null")
||  toolCheck(&toolpath, "xcrun -f dwarfdump 2>/dev/null")
) {
    // use 'toolpath'
}
```

**Comment by charliegracie** [comment]
@genie-omr build all
