### PR TITLE
Replace TreeVerifier with the ILValidator

### LINKED ISSUE #1298: Fix the compiler's Tree Verifier
As reported by #1297, the Tree Verifier in the compiler is not currently behaving as expected.

The Tree Verifier is supposed to check that some given Testarossa Intermediate Language (IL)  is well-formed and conforms to the rules of the language. However, as is shown by the tests in #1297, it is both accepting invalid IL and rejecting valid IL.

Running the test in #1297 using `TR_Options=paranoidoptcheck,tracefull,log=trace.log TR_DEBUG="paranoidoptcheck checkTypes" ./comptest --gtest_filter="TreeVerifierTest/*"` outputs:

```Note: Google Test filter = TreeVerifierTest/*
[==========] Running 15 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 11 tests from TreeVerifierTest/IllformedTrees
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/0
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/0 (78 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/1
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/1 (26 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/2
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/2 (49 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/3
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/3 (497 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/4
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/4 (494 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/5
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/5 (38 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/6
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/6 (43 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/7
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/7 (38 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/8
[       OK ] TreeVerifierTest/IllformedTrees.FailCompilation/8 (27 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/9
../TreeVerifierTest.cpp:34: Failure
Death test: compiler.compile()
    Result: failed to die.
 Error msg:
[  DEATH   ] 
Compilation did not fail due to ill-formed input trees
[  FAILED  ] TreeVerifierTest/IllformedTrees.FailCompilation/9, where GetParam() = "(method \"Int16\" (block (ireturn (scmpeq (sconst 1) (sconst 3)))))" (11 ms)
[ RUN      ] TreeVerifierTest/IllformedTrees.FailCompilation/10
../TreeVerifierTest.cpp:34: Failure
Death test: compiler.compile()
    Result: failed to die.
 Error msg:
[  DEATH   ] 
Compilation did not fail due to ill-formed input trees
[  FAILED  ] TreeVerifierTest/IllformedTrees.FailCompilation/10, where GetParam() = "(method \"Int32\" (block (ireturn (lcmpeq (lconst 1) (lconst 3)))))" (4 ms)
[----------] 11 tests from TreeVerifierTest/IllformedTrees (1311 ms total)

[----------] 4 tests from TreeVerifierTest/WellformedTrees
[ RUN      ] TreeVerifierTest/WellformedTrees.CompileOnly/0
[       OK ] TreeVerifierTest/WellformedTrees.CompileOnly/0 (2 ms)
[ RUN      ] TreeVerifierTest/WellformedTrees.CompileOnly/1
[       OK ] TreeVerifierTest/WellformedTrees.CompileOnly/1 (2 ms)
[ RUN      ] TreeVerifierTest/WellformedTrees.CompileOnly/2
Assertion failed at ../compiler/ras/Tree.cpp:3684: debug("fixTrees")
	Tree verification error
compiling file:line:name at level: warm
#0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x38 [0xa0a1fe]
#1: function TR_Debug::printStackBacktrace()+0x23 [0x770a17]
#2: ./comptest() [0x6c358c]
#3: function TR::assertion(char const*, int, char const*, char const*, ...)+0xb3 [0x6c37cd]
#4: function TR_Debug::verifyTreesPass1(TR::Node*)+0x377 [0x78337f]
#5: function TR_Debug::verifyTreesPass1(TR::Node*)+0x118 [0x783120]
#6: function TR_Debug::verifyTrees(TR::ResolvedMethodSymbol*)+0xd0 [0x782ee4]
#7: function OMR::Compilation::verifyTrees(TR::ResolvedMethodSymbol*)+0xc1 [0x741341]
#8: function OMR::Compilation::compile()+0x7d5 [0x73dc69]
#9: function compileMethodFromDetails(OMR_VMThread*, TR::IlGeneratorMethodDetails&, TR_Hotness, int&)+0x594 [0x9331cd]
#10: function Tril::JitBuilderCompiler::compile()+0x348 [0x6bac88]
#11: function WellformedTrees_CompileOnly_Test::TestBody()+0x4f5 [0x69e095]
#12: function void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x44 [0x7fdeefb5f914]
#13: function testing::Test::Run()+0xba [0x7fdeefb5618a]
#14: function testing::TestInfo::Run()+0x118 [0x7fdeefb562d8]
#15: function testing::TestCase::Run()+0xb5 [0x7fdeefb563b5]
#16: function testing::internal::UnitTestImpl::RunAllTests()+0x257 [0x7fdeefb56697]
#17: function bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x44 [0x7fdeefb5fdc4]
#18: function testing::UnitTest::Run()+0x40 [0x7fdeefb569a0]
#19: function main+0x1f [0x69c20f]
#20: function __libc_start_main+0xea [0x7fdeee8c543a]
#21: function _start+0x2a [0x69cc7a]

comptest: ../compiler/infra/Assert.cpp:140: void assumeDontCallMeDirectlyImpl(const char*, int32_t, const char*, const char*, __va_list_tag*, bool): Assertion `0' failed.
zsh: abort (core dumped)  TR_Options=paranoidoptcheck,tracefull,log=trace.log TR_DEBUG= ./comptest
```

### PR DESCRIPTION
**Pull request by Leonardo2718**
This change takes the previously implemented ILValidator, brings it up to date, and uses it to replace the old TreeVerifier in the compiler component.

This change takes the implementation of the (previously unused) ILValidator and brings it up to date with the rest of the code base. It also implements the necessary mechanisms to dispatch the ILValidator from the optimizer. The `useIlValidator` option is added which, if specified, will cause the optimizer to use the new ILValidator instead of the old TreeVerifier. This will allow downstream projects to continue using the TreeVerifier until they are ready to switch to the new ILValidator. Since the ILValidator is more robust/aggressive than the TreeVerifier, some projects may find that they have to fix problems that were previously unreported. JitBuilder and the test compiler already use the ILValidator by default by hard coding the `useIlValidator` option in their JIT initialization routines.

This change also adds some Tril-based tests for the ILValidator.

Lastly, this change also fixes some of the issues that were reported by the ILValidator during testing. These include both legitimate problems in existing projects as well as problems in the validator itself.

Fixes #1298

### CODE REVIEW

File: jitbuilder/control/Jit.cpp [hunk 1]
```diff
@@ -179,7 +179,7 @@ extern "C"
 bool
 initializeJit()
    {
-   return initializeJitBuilder(0, 0, 0, (char *)"-Xjit:acceptHugeMethods,enableBasicBlockHoisting,omitFramePointer");
+   return initializeJitBuilder(0, 0, 0, (char *)"-Xjit:acceptHugeMethods,enableBasicBlockHoisting,omitFramePointer,useIlValidator");
```
Comment (mgaudet) [inline jitbuilder/control/Jit.cpp]: Do we want the validator turned on by default for JitBuilder? That's a bit surprising to me.

File: compiler/ras/ILValidator.cpp [hunk 2]
```diff
@@ -313,6 +315,36 @@ bool TR::ILValidator::isLoggingEnabled()
    return (comp()->getOption(TR_TraceILWalks));
    }
 
+void TR::ILValidator::printDiagnositc(const char *formatStr, ...)
```
Comment (mgaudet) [inline compiler/ras/ILValidator.cpp]: Typo in name: `Diagnostic` (not `Diagnositc`)

File: compiler/infra/Assert.cpp [hunk 3]
```diff
@@ -38,6 +38,38 @@
 #include "env/VMJ9.h"
 #endif
 
+void OMR_NORETURN TR::trap()
+   {
+   static char * noDebug = feGetEnv("TR_NoDebuggerBreakPoint");
+   if (noDebug)
```
Comment (Leonardo2718) [inline compiler/infra/Assert.cpp]: Fixed.

File: compiler/ras/ILValidator.cpp (hunk 2 above)
Comment (Leonardo2718) [inline compiler/ras/ILValidator.cpp]: Fixed.

File: jitbuilder/control/Jit.cpp (hunk 1 above)
Comment (Leonardo2718) [inline jitbuilder/control/Jit.cpp]: The `useIlValidator` option only makes it so that *if* validation is enabled (e.g. using `paranoidOptCheck`), the ILValidator will be used instead of the TreeVerifier. It does not enable validation by default.

Comment (mgaudet) [inline jitbuilder/control/Jit.cpp]: Ooooooo. 

I see now. 🆒

Thanks!

File: compiler/optimizer/LocalOpts.cpp [hunk 4]
```diff
@@ -8131,7 +8132,7 @@ TR_ColdBlockMarker::perform()
    static char *validate = feGetEnv("TR_validateBeforeColdBlockMarker");
    if (validate)
       {
-      TR::ILValidator validator(this);
+      TR::ILValidator validator(comp());
       validator.checkSoundness(comp()->getStartTree());
```
Comment (0xdaryl) [inline compiler/optimizer/LocalOpts.cpp]: The first thing that `treesAreValid` does is `checkSoundness`.  Is this additional call really needed here?

File: compiler/ras/ILValidator.hpp [hunk 5]
```diff
@@ -0,0 +1,214 @@
...
+
+   TR::Compilation *comp();
+
+   void updateNodeState(Location &newLocation);
+
+   void printDiagnostic(const char *formatStr, ...);
+   void vprintDiagnostic(const char *formatStr, va_list ap);
+   };
+
+class JavaILValidator: public ILValidator
```
Comment (Leonardo2718) [inline compiler/ras/ILValidator.hpp]: Originally, `JavaILValidator` was in `omr/compiler/infra/ILWalk.{hpp,cpp}`. It just got moved around as part of my refactoring. I've removed it from the OMR compiler though and it will now live as part of the Java project.

File: compiler/optimizer/LocalOpts.cpp (hunk 4 above)
Comment (Leonardo2718) [inline compiler/optimizer/LocalOpts.cpp]: This is how it was previously implemented. I'll remove though because it really is redundant.

File: compiler/ras/ILValidator.cpp [hunk 6]
```diff
@@ -0,0 +1,356 @@
...
+
+static bool hasGlRegDeps(TR::Node* node)
+   {
+   for (auto i = 0; i < node->getNumChildren(); ++i)
+      {
+      if (node->getChild(i)->getOpCodeValue() == TR::GlRegDeps)
+         {
+         return true;
+         }
+      }
```
Comment (vijaysun-omr) [inline compiler/ras/ILValidator.cpp]: Yes it should be the last child in every case I know of.

File: compiler/infra/Assert.hpp [hunk 7]
```diff
@@ -21,6 +21,9 @@
  *
  * Defines a number of assert macros.
```
Comment (Leonardo2718) [inline compiler/infra/Assert.hpp]: Very true. Fixed!

File: compiler/il/ILOpCodeProperties.hpp [hunk 8]
```diff
@@ -1627,7 +1627,7 @@
    /* .properties4          = */ 0,
    /* .dataType             = */ TR::Int32,
    /* .typeProperties       = */ ILTypeProp::Size_4 | ILTypeProp::Integer,
-   /* .childProperties      = */ TWO_SAME_CHILD(TR::Int32),
+   /* .childProperties      = */ TWO_CHILD(TR::Int32, TR::Int32),
```
Comment (Leonardo2718) [inline compiler/il/ILOpCodeProperties.hpp]: I'm afraid this nothing more than an automated refactoring artifact :sweat_smile:. Fixed!

File: compiler/infra/ILWalk.hpp [hunk 9]
```diff
@@ -60,15 +59,17 @@ class TreeTopIteratorImpl
...
+
+   TR::Compilation * comp() { return _comp; }
 
    void logCurrentLocation();
 
    void stepForward();
    void stepBackward();
 
-   TreeTopIteratorImpl(TR::TreeTop *start, TR::Optimization *opt=NULL, const char *name=NULL);
+   TreeTopIteratorImpl(TR::TreeTop *start, TR::Compilation *comp=NULL, const char *name=NULL);
```
Comment (Leonardo2718) [inline compiler/infra/ILWalk.hpp]: In the original implementation, it was the `TR::Optimization` that was optional. I just changed the type of the parameter.

I don't think it makes sense for these APIs to be used outside of a compilation, since they operate exclusive on the compiler's IL, which is only (currently) available during compilation.

Personally, I would prefer if the parameter was mandatory, but I think making this change is outside the scope of this already large pull request.

File: compiler/ras/ILValidator.cpp [hunk 10]
```diff
@@ -0,0 +1,356 @@
...
+         }
+      else
+         {
+         soundnessRule(currentTree, stop == NULL, "Reached the end of the trees after n%dn without encountering the stop tree n%dn", currentTree->getNode()->getGlobalIndex(), stop? stop->getNode()->getGlobalIndex() : 0);
+         checkNodeSoundness(currentTree, currentTree->getNode(), ancestorNodes, visitedNodes);
+         }
+      }
+   }
+
+void TR::ILValidator::checkNodeSoundness(TR::TreeTop *location, TR::Node *node, NodeChecklist &ancestorNodes, NodeChecklist &visitedNodes)
```
Comment (Leonardo2718) [inline compiler/ras/ILValidator.cpp]: I didn't originally write this code, I only moved it from `compiler/ras/ILWalk.cpp`, so I can only make educated guesses for why it was written this way.

However, I believe the reason for calling the first parameter `location` is that it is only used to print the "location" of a failure in diagnostic messages; it is not actually used to check anything. In this sense, it keeps the interface consistent with the rest of the API.

I actually prefer the name `location` to `treetop` because it makes the purpose of the parameter clear: to specify where the node being checked is "located". However, I'm open to re-naming it to something like `treetopLocation` or `parentTreetop`. Both of these names make the relationship with the `node` parameter clear (at least in my head).

File: compiler/ras/ILValidator.cpp [hunk 11]
```diff
@@ -0,0 +1,356 @@
...
+      TR::Node *child = node->getChild(i);
+      soundnessRule(location, child != NULL, "n%dn child %d must not be NULL", node->getGlobalIndex(), i);
+
+      checkNodeSoundness(location, child, ancestorNodes, visitedNodes);
+      }
+
+   ancestorNodes.remove(node);
+   }
+
+void TR::ILValidator::soundnessRule(TR::TreeTop *location, bool condition, const char *formatStr, ...)
```
Comment (Leonardo2718) [inline compiler/ras/ILValidator.cpp]: Same comment as above.

File: compiler/ras/ILValidator.cpp (hunk 6 above)
Comment (Leonardo2718) [inline compiler/ras/ILValidator.cpp]: If this is indeed the case, I'm open to changing this.

Comment (andrewcraik) [inline compiler/ras/ILValidator.cpp]: If it isn't last I think it will surprise a lot of other code.

File: compiler/ras/ILValidator.cpp [hunk 12]
```diff
@@ -0,0 +1,340 @@
...
+
+      //
+      // Additional specific kinds of validation
+      //
+
+      TR::Node *node = iter.currentNode();
+      if (node->getOpCodeValue() == TR::BBEnd)
+         {
+         // Determine whether this is the end of an extended block
+         //
```
Comment (andrewcraik) [inline compiler/ras/ILValidator.cpp]: There would be an opportunity here to catch another kind of oops - where you have broken a block and failed to extend when it makes sense to do so. This would be more of a warning, but it could be a nice extra in another iteration to check if there is a single successor, single predecessor relationship and block extension has been run then we should expect the next block to be marked an extension.

Comment (Leonardo2718) [inline compiler/ras/ILValidator.cpp]: This does sound like something that could be worth checking. Is there a reason this couldn't be done in the CFGVerifier instead?

Comment (andrewcraik) [inline compiler/ras/ILValidator.cpp]: Probably not - it just occurred to me while I was reading all the code about checking extension here.

File: compiler/ras/ILValidator.cpp (hunk 6 above)
Comment (Leonardo2718) [inline compiler/ras/ILValidator.cpp]: Excellent! Fixed!

File: compiler/ras/ILValidator.cpp [hunk 13]
```diff
@@ -0,0 +1,339 @@
...
+               const auto actChildType = childOpcode.getDataType().getDataType();
+               const auto expChildTypeName = expChildType == ILChildProp::UnspecifiedChildType ? "UnspecifiedChildType" : TR::DataType::getName(expChildType);
+               const auto actChildTypeName = TR::DataType::getName(actChildType);
+               validityRule(iter, expChildType == ILChildProp::UnspecifiedChildType || actChildType == expChildType,
+                            "Child %d has unexpected type %s (expected %s)" , i, actChildTypeName, expChildTypeName);
+               }
+            else
+               {
+               // make sure the node is allowed to have a GlRegDeps child
+               // and make sure that it is the last child
```
Comment (mgaudet) [inline compiler/ras/ILValidator.cpp]: 👍 Nice. I was happy to see that got converted to a validity rule.

File: compiler/infra/ILWalk.hpp (hunk 9 above)
Comment (0xdaryl) [inline compiler/infra/ILWalk.hpp]: I think the parameter should be mandatory too.  I don't quite understand your "scope" comment though because to fix this is simply a matter of removing the default value.  If there are places in the code that rely on the default value and don't pass in a valid compilation object I would argue that they are now potentially incorrect anyway because some of the underlying validator code relies on having a compilation object (whose access is not always guarded).

Comment (Leonardo2718) [inline compiler/infra/ILWalk.hpp]: Fair enough.

**Comment by Leonardo2718** [comment]
Thanks @0xdaryl!

> Given recent experiences with memory leaks in other data structures I think the data structures supporting IL validation need a comprehensive review as well to be sure their lifetimes are understood and memory is reclaimed accordingly. I don't think this should hold up merging this initial PR, but I do think its something that needs to get done before this technology become ubiquitous.

Completely agree. I'll open an issue to track this once the PR is merged.

> It is unfortunate that the shiftOrRol name from the Test compiler got morphed into "shift and roll" which I don't think makes sense (unless I'm way off the mark on the context). It's likely named as such because OMR only supports a rotate left opcode, which I'm a bit surprised to discover only now! The Test compiler tests should have been more aptly named shiftAndRotate, and hence your descendants written in Tril should be named accordingly and avoid the mis-named "roll". I'd like this to be fixed in your Tril implementation and commit messages before this gets merged to avoid perpetuating confusion.

Should be fixed now.

> I appreciate the effort you put into re-writing the invalid shiftOrRol tests in Tril. As we are actively working to upgrade the Google Test framework in order to enable Tril as part of TravisCI I am fine with deprecating the Test compiler tests as you have done so in this PR. I doubt this is leaving us exposed to any significant extent on the quality front for a short period of time.

Agreed. Hopefully we can get Tril enable as soon :slightly_smiling_face:.

File: compiler/ras/ILValidator.cpp (hunk 10 above)
Comment (0xdaryl) [inline compiler/ras/ILValidator.cpp]: Alright, it can stay the way it is.

File: compiler/ras/ILValidator.cpp (hunk 11 above)
Comment (0xdaryl) [inline compiler/ras/ILValidator.cpp]: Same reply as above.

**Comment by 0xdaryl** [comment]
@mgaudet , please approve Leo's changes if you're OK with them.  I'll merge once you've signed off.
