### PR TITLE
FIX #112 make thread abort test startup more reliable

### LINKED ISSUE #112: thread abort test start up is unreliable
The test in fvtest/threadtest/abortTest.cpp relies on a thread being started within 1 second before issuing the abort request. This test should really synchronize the threads to ensure the second thread has been started before the abort request is issued, or else the test can fail erroneously (see PR #91).

### PR DESCRIPTION
**Pull request by mstoodle**
Add synchronization at the beginning of the test so that the dependent thread (to be aborted)
is known to have started when the abort is issued. With this change, it's (still) possible the dependent
thread won't be actually running or sleeping as the test intends, but the abort should never be
missed which should make the test more reliable.

Signed-off-by: Mark Stoodley <mstoodle@ca.ibm.com>

### CODE REVIEW

**Comment by mstoodle** [comment]
Sadness: failures unrelated to my change, I think:

forkResetTest.cpp:308: Failure
Value of: 0 == testdata.rc
  Actual: false
Expected: true
Failure occurred in child process.

then later:
forkResetTest.cpp:147: Failure
Value of: 0 == testdata.rc
  Actual: false
Expected: true
Failure occurred in child process.

**Comment by mstoodle** [comment]
Bad Mark for not updating on progress here.

The most recent state of this "fix" is that I haven't been able to nail down just why the forkReset test started 100% failing when I apply the fix for the abortTest. I'll try to spend time on the forkReset test over the next week so this problem can get wrapped up. As it stands, the intermittent failure in the abort test is not nearly so dangerous as the 100% failure in forkReset if you apply my fix, so I'm leaving it out for now.

**Comment by mstoodle** [comment]
Ok, it was related to my change. Braindead forgetting to destroy the additional monitors I created to synchronize threads at the start of the thread abort tests. Fix should be forthcoming shortly.

File: fvtest/threadtest/abortTest.cpp [hunk 1]
```diff
@@ -112,26 +129,37 @@ runningMain(void *arg)
...
+	omrthread_monitor_t startSync;
 	omrthread_monitor_t exitSync;
 	volatile intptr_t rc;
+	volatile bool started;
 } sleep_testdata_t;
 
 TEST(ThreadAbortTest, Sleeping)
 {
 	omrthread_t t;
 	sleep_testdata_t mythread;
```
Comment (charliegracie) [inline fvtest/threadtest/abortTest.cpp]: should we be setting mythread.started = false?

Comment (mstoodle) [inline fvtest/threadtest/abortTest.cpp]: good point. fixed it :) Thanks!
