### PR TITLE
Fix sign-extension bug in byte/short to float/double conversion on x86

### LINKED ISSUE #5378: X86 byte/short to floating point evaluator error
Found the following bug by running `fvtest/compilertest` under X86 windows.
```
[ RUN      ] JITX86OpCodesTest.UnaryTest
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1705): error:       Expected: convert(byteDataArray[i], FLOAT_POS)
26:       Which is: -9
26: To be equal to: _b2f(byteDataArray[i])
26:       Which is: 247
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1706): error:       Expected: convert(byteDataArray[i], DOUBLE_POS)
26:       Which is: -9
26: To be equal to: _b2d(byteDataArray[i])
26:       Which is: 247
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1705): error:       Expected: convert(byteDataArray[i], FLOAT_POS)
26:       Which is: -128
26: To be equal to: _b2f(byteDataArray[i])
26:       Which is: 128
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1706): error:       Expected: convert(byteDataArray[i], DOUBLE_POS)
26:       Which is: -128
26: To be equal to: _b2d(byteDataArray[i])
26:       Which is: 128
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1777): error:       Expected: convert(shortDataArray[i], FLOAT_POS)
26:       Which is: -9
26: To be equal to: _s2f(shortDataArray[i])
26:       Which is: 65527
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1778): error:       Expected: convert(shortDataArray[i], DOUBLE_POS)
26:       Which is: -9
26: To be equal to: _s2d(shortDataArray[i])
26:       Which is: 65527
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1777): error:       Expected: convert(shortDataArray[i], FLOAT_POS)
26:       Which is: -32768
26: To be equal to: _s2f(shortDataArray[i])
26:       Which is: 32768
26: D:\a\1\s\fvtest\compilertest\tests\X86OpCodesTest.cpp(1778): error:       Expected: convert(shortDataArray[i], DOUBLE_POS)
26:       Which is: -32768
26: To be equal to: _s2d(shortDataArray[i])
26:       Which is: 32768
26: [  FAILED  ] JITX86OpCodesTest.UnaryTest (323 ms)

```
Currently the X86 evaluators that are handling `b2f`, `b2d`, `s2f`, `s2d` ILOpcodes are causing an error when converting from a negative value. Specifically, the evaluation routine correctly sign extends the value, but failed to load the sign extended value using 2's complement. e.g. -9 (0b0000 1001) are falsely converted to 247(0b0111 10111) by b2f; converted to 65527(0b1111 1111 1111 0111) by b2d.

### PR DESCRIPTION
**Pull request by AGDNoob**
## Problem

The `i2fEvaluator` and `i2dEvaluator` fast path in `FPTreeEvaluator.cpp` used `CVTSI2SS`/`CVTSI2SD` with a 32-bit memory operand for **all** integer-to-float opcodes, including `b2f`, `s2f`, `b2d`, and `s2d`.

These instructions always read 32 bits from memory. For byte (8-bit) and short (16-bit) source types, the upper bits contain uninitialized data and no sign-extension occurs, producing incorrect results for negative values.

## Fix

Restrict the memory-operand fast path to only `i2f` and `i2d` opcodes by adding a check for `node->getOpCodeValue()`. Sub-integer conversions (`b2f`, `s2f`, `b2d`, `s2d`) now take the general path which correctly applies `MOVSX` before the SSE conversion.

## Testing

Re-enabled the byte/short to float/double conversion tests in `X86OpCodesTest.cpp` that were previously skipped due to this bug. All 45 compiler tests pass, including negative value cases that previously failed.

Closes: #5378

### CODE REVIEW

File: compiler/x/codegen/FPTreeEvaluator.cpp [hunk 1]
```diff
@@ -631,7 +631,8 @@ TR::Register *OMR::X86::TreeEvaluator::i2fEvaluator(TR::Node *node, TR::CodeGene
     TR::Register *target;
     TR::MemoryReference *tempMR;
 
-    if (child->getRegister() == NULL && child->getReferenceCount() == 1 && child->getOpCode().isLoadVar()) {
+    if (node->getOpCodeValue() == TR::i2f && child->getRegister() == NULL && child->getReferenceCount() == 1
```
Comment (hzongaro) [inline compiler/x/codegen/FPTreeEvaluator.cpp:640]: May I ask you to add a comment indicating why this has to be limited to `i2f`?

File: compiler/x/codegen/FPTreeEvaluator.cpp [hunk 2]
```diff
@@ -675,7 +676,8 @@ TR::Register *OMR::X86::TreeEvaluator::i2dEvaluator(TR::Node *node, TR::CodeGene
     TR::Register *target;
     TR::MemoryReference *tempMR;
 
-    if (child->getRegister() == NULL && child->getReferenceCount() == 1 && child->getOpCode().isLoadVar()) {
+    if (node->getOpCodeValue() == TR::i2d && child->getRegister() == NULL && child->getReferenceCount() == 1
```
Comment (hzongaro) [inline compiler/x/codegen/FPTreeEvaluator.cpp:689]: May I ask you to add a comment indicating why this has to be limited to `i2d`?

File: fvtest/compilertest/tests/X86OpCodesTest.cpp [hunk 3]
```diff
@@ -1702,12 +1702,8 @@ X86OpCodesTest::invokeUnaryTests()
...
       OMR_CT_EXPECT_EQ(_b2i, convert(byteDataArray[i], INT_POS), _b2i(byteDataArray[i]));
       OMR_CT_EXPECT_EQ(_b2l, convert(byteDataArray[i], LONG_POS), _b2l(byteDataArray[i]));
-      if (byteDataArray[i] >= 0)
-            // Skip char to fp conversion on X86: Known bug, see Issue #5378
-            {
-            OMR_CT_EXPECT_FLOAT_EQ(_b2f, convert(byteDataArray[i], FLOAT_POS), _b2f(byteDataArray[i]));
-            OMR_CT_EXPECT_DOUBLE_EQ(_b2d, convert(byteDataArray[i], DOUBLE_POS), _b2d(byteDataArray[i]));
-            }
+      OMR_CT_EXPECT_FLOAT_EQ(_b2f, convert(byteDataArray[i], FLOAT_POS), _b2f(byteDataArray[i]));
+      OMR_CT_EXPECT_DOUBLE_EQ(_b2d, convert(byteDataArray[i], DOUBLE_POS), _b2d(byteDataArray[i]));
```
Comment (hzongaro) [inline fvtest/compilertest/tests/X86OpCodesTest.cpp:1708]: Perhaps tests of `bu2f` and `bu2d` should be added.

File: fvtest/compilertest/tests/X86OpCodesTest.cpp [hunk 4]
```diff
@@ -1778,12 +1774,8 @@ X86OpCodesTest::invokeUnaryTests()
...
       OMR_CT_EXPECT_EQ(_s2i, convert(shortDataArray[i], INT_POS), _s2i(shortDataArray[i]));
       OMR_CT_EXPECT_EQ(_s2l, convert(shortDataArray[i], LONG_POS), _s2l(shortDataArray[i]));
-      if (byteDataArray[i] >= 0)
-            // Skip short to fp conversion on X86: Known bug, see Issue #5378
-            {
-            OMR_CT_EXPECT_FLOAT_EQ(_s2f, convert(shortDataArray[i], FLOAT_POS), _s2f(shortDataArray[i]));
-            OMR_CT_EXPECT_DOUBLE_EQ(_s2d, convert(shortDataArray[i], DOUBLE_POS), _s2d(shortDataArray[i]));
-            }
+      OMR_CT_EXPECT_FLOAT_EQ(_s2f, convert(shortDataArray[i], FLOAT_POS), _s2f(shortDataArray[i]));
+      OMR_CT_EXPECT_DOUBLE_EQ(_s2d, convert(shortDataArray[i], DOUBLE_POS), _s2d(shortDataArray[i]));
```
Comment (hzongaro) [inline fvtest/compilertest/tests/X86OpCodesTest.cpp:1780]: Perhaps tests of `su2f` and `su2d` should be added.

**Review by hzongaro — COMMENTED** [review]
I think your change looks correct.  I just have a couple of suggestions for comments and additional testing.

Also, as you used Generative AI to assist with authoring this pull request, please see this guidance on [Attribution](https://github.com/eclipse-omr/omr/blob/master/CONTRIBUTING.md#attribution).  In particular, please add a line to any source files below the copyright comments indicating which AI assistant you used, and include the “Co-authored by” line for the AI assistant on your commit comment before your own “Signed-off-by” line.

Finally, the lines in the commit comment are longer than the recommended 72 characters per ~~long~~ line.  Please take a look at the [Commit Guidelines](https://github.com/eclipse-omr/omr/blob/master/CONTRIBUTING.md#commit-guidelines) for more details on how it should  be formatted.

**Comment by AGDNoob** [comment]
Thanks for the review @hzongaro. I have pushed an update that addresses all points:

* Added `// Some sections generated by Claude Opus 4.7 (Anthropic)` below the copyright header in `FPTreeEvaluator.cpp` and `X86OpCodesTest.cpp`.
* Added `Co-authored by Claude Opus 4.7 (Anthropic)` to the commit message before my `Signed-off-by`.
* Reformatted the commit body to stay within 72 characters per line.
* Added a comment above each guarded `if` explaining that `CVTSI2SS` / `CVTSI2SD` read 32 bits from memory unconditionally, so only `i2f` / `i2d` can take the memory-operand fast path while `b2f` / `bu2f` / `s2f` / `su2f` (and the corresponding `2d` variants) must fall through to the register form that widens the operand with `MOVSX` / `MOVZX` first.

On the suggestion to add `bu2f` / `bu2d` and `su2f` / `su2d` tests: those already exist further down in `invokeUnaryTests()`. The `bu2*` cases are covered around line 1746 using `ubyteDataArray`, and the `su2*` cases around line 1810 using `ushortDataArray`. They were not gated by the #5378 workaround, so no change was needed there.

File: fvtest/compilertest/tests/X86OpCodesTest.cpp (hunk 4 above)
Comment (hzongaro) [reply fvtest/compilertest/tests/X86OpCodesTest.cpp:1780]: Tests already exist, as noted as noted in the [comment](#issuecomment-4307122532) below.

File: fvtest/compilertest/tests/X86OpCodesTest.cpp (hunk 3 above)
Comment (hzongaro) [reply fvtest/compilertest/tests/X86OpCodesTest.cpp:1708]: Tests already exist, as noted as noted in the [comment](#issuecomment-4307122532) below.

File: compiler/x/codegen/FPTreeEvaluator.cpp (hunk 1 above)
Comment (hzongaro) [reply compiler/x/codegen/FPTreeEvaluator.cpp:640]: Comment added in commit 283aa4ccebb629bfca34bdba8037fa169a5acc4e

File: compiler/x/codegen/FPTreeEvaluator.cpp (hunk 2 above)
Comment (hzongaro) [reply compiler/x/codegen/FPTreeEvaluator.cpp:689]: Comment added in commit 283aa4ccebb629bfca34bdba8037fa169a5acc4e

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins build xlinux,x32linux,osx,win

**Comment by hzongaro** [comment]
Testing completed successfully.  The change restricts the cases in which an existing optimization applies, so it is very safe.  Merging.
