### PR TITLE
DDRgen macro constant expression evaluation

### LINKED ISSUE #2100: Improve ddrgen handling of constant expressions
The tool ddrgen needs to capture constants in the blob it generates. Currently it doesn't do such a good job.

For example,
```
#define MASK (0x1 | 0x2 | 0x4)
```
only considers the first number it finds inside the inner-most set of parentheses and interprets `0x1` as `0`.

Even if those flags were not expressed in hexadecimal,
```
#define MASK (1 | 2 | 4)
```
it would see `1` which is still the wrong answer.

Several constants defined by OMR (or OpenJ9 which is likely to be the first consumer of ddrgen) use C operators: these need to be properly handled by ddrgen. The full list of C operators in order of precedence is available at http://en.cppreference.com/w/c/language/operator_precedence.

The problem is well-contained in Macro::getNumeric(long long *).

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
Adds a recursive descent parser in order to parse macros that contain
constant expressions which evaluate down to integers.
The final constant value is returned as a `long long` in order to keep
compatibility with the rest of the ddr components.

Closes #2100

Signed-off-by: mikezhang <mike.h.zhang@ibm.com>

### CODE REVIEW

**Comment by mikezhang1234567890** [comment]
Reviewer: @keithc-ca

File: ddr/include/ddr/ir/Macro.hpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*******************************************************************************
- * Copyright (c) 2015, 2017 IBM Corp. and others
+ * Copyright (c) 2015, 2018 IBM Corp. and others
```
Comment (keithc-ca) [inline ddr/include/ddr/ir/Macro.hpp]: Please revert this change.

Comment (fjeremic) [reply ddr/include/ddr/ir/Macro.hpp]: > Please revert this change.

From an outside perspective, any reason why? Was this file crafted in 2017 and unchanged in the new year?

Comment (keithc-ca) [reply ddr/include/ddr/ir/Macro.hpp]: That's right; the copyright date only needs to be updated if the file was changed (in some other way).

File: ddr/lib/ddr-ir/Macro.cpp [hunk 2]
```diff
@@ -26,56 +26,563 @@
...
+/* function members */
+private:
+	bool binaryExpression(int64_t *, binExpr_type);
+	bool unaryExpression(int64_t*);
+	bool parentheses(int64_t*);
+	bool readNumber(int64_t*);
+	void skipWhitespace();
+
+public:
+	MacroParser(std::string expression) : _expression(expression), _index(0)
```
Comment (charliegracie) [inline ddr/lib/ddr-ir/Macro.cpp]: The variables are being initialized in the wrong order.  They need to be initialized in declaration order since that is the order they will *actually* be initialized in. 

Could you also move them each onto their own line for clarity?

**Comment by mikezhang1234567890** [comment]
@keithc-ca Can you review again please?

File: ddr/lib/ddr-ir/Macro.cpp [hunk 3]
```diff
@@ -25,57 +25,951 @@
...
+	RPAREN		/* ) */
+};
+
+class MacroScanner
 {
-	DDR_RC rc = DDR_RC_OK;
-	string value = getValue();
+private:
+	char const *_cursor;
+	char const *_end;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: I don't think this field (`_end`) is required.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 4]
```diff
@@ -25,57 +25,951 @@
...
+	MacroScanner(string expression) :
+		_cursor(expression.c_str()),
+		_end(_cursor + expression.length())
+	{
+	}
+
+	bool atSymbol(Symbol sym);
+	bool readNumber(int64_t *ret);
+
+	friend class MacroParser;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: Make the required methods public rather than use a friend declaration.

FYI, there should be a forward declaration for `class MacroParser` before it can be meaningfully referenced in a friend declaration.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 5]
```diff
@@ -25,57 +25,951 @@
...
-			ss << value;
-			long long valueNumeric = 0;
-			ss >> valueNumeric;
-			if (ss.fail()) {
-				rc = DDR_RC_ERROR;
-			} else if (NULL != ret) {
-				*ret = valueNumeric;
-			}
+	MacroScanner(string expression) :
+		_cursor(expression.c_str()),
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: Change the signature of the constructor so the argument is of type `const char *`. As written, `_cursor` points at memory that will soon be freed.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 6]
```diff
@@ -25,57 +25,951 @@
...
+ * Helper function to read the value of a number from a string, this checks if
+ * a character is a digit in a specified base
+ *
+ * @param[in] c: character being checked
+ * @param[in] base: the base used to check if the char is valid
+ *
+ * @return: if the character is a valid digit in the specified base
+ */
+static bool
+isadigit(char c, int base)
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: This function (and 'digitvalue') should be private static methods of MacroScanner.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 7]
```diff
@@ -25,57 +25,951 @@
...
+			return true;
+		}
+		break;
+	case RPAREN:
+		if (')' == _cursor[0]) {
+			_cursor += 1;
+			return true;
+		}
+		break;
+	}
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: A switch statement should always have a default case.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 8]
```diff
@@ -25,57 +25,951 @@
...
+/**
+ * Reads an integer number starting at the cursor in the expression string.
+ * Number is read as a 64bit integer.
+ */
+bool
+MacroScanner::readNumber(int64_t *ret)
+{
+	uint64_t retval = 0;
+	int base = 0;
+	bool negative = false;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: A `-` character is not part of a numeric literal - it is the unary negation operator.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 9]
```diff
@@ -25,57 +25,951 @@
...
+	for (int i= 0; (_cursor < _end) && (i < 3); i++, _cursor++) {
+		if (('l' == _cursor[0]) || ('L' == _cursor[0]) ) {
+			numL += 1;
+		} else if (('u' == _cursor[0]) || ('U' == _cursor[0])){
+			numU += 1;
+		} else {
+			break;
+		}
+	}
+	if (2 < numL || 1 < numU) {
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: Parentheses missing here.
I personally find it difficult to read such comparisons: I think `((numL > 2) || (numU > 1))` is clearer.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 10]
```diff
@@ -25,57 +25,951 @@
...
+ * @return: whether the expression is valid or not
+ */
+bool
+MacroParser::evaluate(int64_t *ret)
+{
+	bool validExpr = logicalOr(ret);
+	if (validExpr) {
+		return true;
+	}
+	return false;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: This can be just `return logicalOr(ret);`.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 11]
```diff
@@ -25,57 +25,951 @@
...
+ *
+ * @param[out] ret: the integer value the logical or expression evaluates to
+ *
+ * @return: whether the at the current index the expression can be evaluated
+ */
+bool
+MacroParser::logicalOr(int64_t *ret)
+{
+	int64_t term1 = 0;
+	int64_t term2 = 0;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: Why not just use `ret` and `term2`? What value is added by declaring `term1`?

File: ddr/lib/ddr-ir/Macro.cpp [hunk 12]
```diff
@@ -25,57 +25,951 @@
...
+ * @return: whether the at the current index the expression can be evaluated
+ */
+bool
+MacroParser::multDivRem(int64_t *ret)
+{
+	int64_t term1 = 0;
+	int64_t term2 = 0;
+
+	if (unaryExpression(&term1) || parentheses(&term1)
+			|| _scanner.readNumber(&term1)) {
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: I think another method is warranted to encapsulate the recurring pattern:
```
unaryExpression(X) || parentheses(X) || _scanner.readNumber(X)
```

File: ddr/lib/ddr-ir/Macro.cpp [hunk 13]
```diff
@@ -25,57 +25,951 @@
...
+ * applies a unary typecast operator
+ *
+ * @param[in] typeExpr: string representing the types inside a typecast operator
+ * @param[in] operand: value of the operand the typecast is being applied to
+ * @param[out] ret: value after the typecast has been applied
+ *
+ * @return: whether the typecast is valid and has been successfully applied
+ */
+static bool
+typeCast(const string typeExpr, int64_t operand, int64_t *ret)
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: I think we should first just ignore casts (besides, this doesn't handle things like `uintptr_t` or `UDATA`).

Removing the friendship between the scanner and parser classes will require some rework. I expect the scanner will need to recognize a sequence of words separated by whitespace for use by the parser to handle casts.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 14]
```diff
@@ -25,57 +25,951 @@
...
+ */
+DDR_RC
+Macro::getNumeric(long long *ret)
+{
+	DDR_RC rc = DDR_RC_ERROR;
+	string value = getValue();
+	int64_t retVal = 0;
+	MacroParser parser(value);
+	if (parser.evaluate(&retVal)) {
+		*ret = retVal;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: This must first check that `NULL != ret`.

**Comment by mikezhang1234567890** [comment]
@keithc-ca Can you please take another look?

**Comment by charliegracie** [comment]
@genie-omr build all

File: ddr/lib/ddr-ir/Macro.cpp [hunk 15]
```diff
@@ -21,53 +21,962 @@
...
+	bool bitshift(int64_t *ret);
+	bool addSub(int64_t *ret);
+	bool multDivRem(int64_t *ret);
+	bool unaryExpression(int64_t *ret);
+	bool parentheses(int64_t *ret);
+	bool validSingleTerm(int64_t *ret);
+
+public:
+	MacroParser(std::string expression) :
+		_scanner(expression.c_str())
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: This leads to a dangling pointer.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 16]
```diff
@@ -21,53 +21,962 @@
...
+				validTypes = true;
+			} else if ((1 >= numSigned + numUnsigned) && (0 == numChar)
+					&& (0 == numShort) && (0 == numInt) && (0 == numLong)) {
+				*bitWidth = 0;
+				validTypes = true;
+			}
 		}
+	}
+	if (!validTypes) {
+		_cursor = typecastStart - 1;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: Why the `- 1`? Shouldn't it restore _cursor to the value on entry?

Comment (mikezhang1234567890) [reply ddr/lib/ddr-ir/Macro.cpp]: It restores `_cursor` to the `(` symbol before the string of types.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 17]
```diff
@@ -21,53 +21,962 @@
...
+		size_t bitWidth = 0;
+		bool isSigned = true;
+		if (_scanner.validTypeCast(&isSigned, &bitWidth)
+				&& _scanner.atSymbol(RPAREN) && validSingleTerm(&operand)) {
+			switch(bitWidth) {
+			case 0:
+				*ret = (isSigned) ? (signed) operand : (unsigned) operand;
+				break;
+			case 8:
+				*ret = (isSigned) ? (int8_t) operand : (size_t) operand;
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: The second cast should be `(uint8_t) operand`.

File: ddr/lib/ddr-ir/Macro.cpp (hunk 16 above)
Comment (keithc-ca) [reply ddr/lib/ddr-ir/Macro.cpp]: That would be reasonable if the scanner (rather than the parser) considered the opening parenthesis.

File: ddr/lib/ddr-ir/Macro.cpp [hunk 18]
```diff
@@ -21,53 +21,975 @@
...
+ *
+ * return: DDR return code indicating success or error
+ */
+DDR_RC
+Macro::getNumeric(long long *ret) const
+{
+	DDR_RC rc = DDR_RC_ERROR;
+	string value = getValue();
+	int64_t retVal = 0;
+	MacroParser parser(value.c_str());
```
Comment (keithc-ca) [inline ddr/lib/ddr-ir/Macro.cpp]: There's no need to make a copy of `_value` here; the parser can be constructed from `_value.c_str()`.

**Comment by charliegracie** [comment]
@mikezhang1234567890  can you squash the commits into the correct amount of logical changes (likely just 1)?  Thanks

**Comment by mikezhang1234567890** [comment]
Made changes as requested and squashed commits. Is there anything else that needs addressing? @keithc-ca @charliegracie
